### ISSUE TITLE
Element has class

### ISSUE THREAD

**Issue by nishudixit** [wlsf82/protractor-helper#101]
**Is your feature request related to a problem? Please describe.**
I couldn't find in existing functions like to check if the element has class

**Describe the solution you'd like**
It would be good if something to check for the class present in an element like `waitForClassToBePresentInElement`

**Comment by wlsf82** [comment]
Hi, @nishudixit, that's a great idea, thanks!

I'll spend some time on it this week, and I'll keep you posted.

FYI, @PauloGoncalvesBH.

**Comment by wlsf82** [comment]
Until then, I recommend you to use Protractor's `getAttribute` method (http://www.protractortest.org/#/api?view=webdriver.WebElement.prototype.getAttribute.)

**Comment by nishudixit** [comment]
Yes I am using the same @wlsf82 Thanks!

**Comment by wlsf82** [comment]
This is not gonna be implemented, and so I'm closing the issue.

**Comment by nishudixit** [comment]
> 
> 
> This is not gonna be implemented, and so I'm closing the issue.

ok, thanks!
