### ISSUE TITLE
waitForElementVisibility not giving appropriate validation message

### ISSUE THREAD

**Issue by nishudixit** [wlsf82/protractor-helper#103]
**Describe the bug**
I'm using protractorHelper for non angular website with cucumber js. I have set the value of waitForAngularEnabled to false, now I've observed that sometimes it gives error `Error: function timed out, ensure the promise resolves within 5000 milliseconds` for wait condition

**Actual Error**
`Then I add new clinical item with name "test new clinical item" # src\clinical-items-builder\step-definitions\clinical-items-builder.steps.js:38`
`Error: function timed out, ensure the promise resolves within 5000 milliseconds`

**Wait condition**
`protractorHelper.waitForElementVisibility(element(by.css('.someclass');`

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser chrome
- Version 86.0.4240.183

**Comment by wlsf82** [comment]
Hi, @nishudixit, is `.someclass` just an example, or is it the real selector you're using? If so, are you sure you have an element with such a generic class?\

If so, I'd need some snippets of your code to help you out.

Could you please provide me with the snippets of the test file, config file, feature files, page objects (if you use them), etc?

**Comment by nishudixit** [comment]
@wlsf82 it was just an example, sorry for the confusion.

**Comment by wlsf82** [comment]
> @wlsf82 it was just an example, sorry for the confusion.

So, @nishudixit, will you send me the code so that we can investigate why your test is failing?

**Comment by wlsf82** [comment]
@nishudixit, I'm closing this issue since I got no response from you. Feel free to re-open it in case you still have the issue, but then, reply to my comments, please. 😄
