### ISSUE TITLE
Update README.md file with a section about its translated version

### ISSUE THREAD

**Issue by wlsf82** [wlsf82/protractor-helper#110]
Now that the translation to PT-BR is finished, it'd be nice to have a section on the English version of it, mentioning the PT-BR one.

**Comment by pedrohyvo** [comment]
@wlsf82 I'd like to work on this issue. Do you have any suggestions for where's the best place to add it in our README content? Also could you assign to me, please

**Comment by wlsf82** [comment]
> @wlsf82 I'd like to work on this issue. Do you have any suggestions for where's the best place to add it in our README content? Also could you assign to me, please

Hi, @pedrohyvo, I've no preferences. What about right after the External resources section?
Or, just put it somewhere else on your PR, and let's see how it looks.
By the way, thanks for the interest in contributing!

Ah, I've assigned the issue to you. 🚀

**Comment by pedrohyvo** [comment]
@wlsf82 I added a link at the top because I think it has more visibility there since nobody will scroll down to check if there's a portuguese version available. Let me know your concerns please

**Comment by wlsf82** [comment]
Closed by https://github.com/wlsf82/protractor-helper/pull/113
