### ISSUE TITLE
Add method waitForAlertToBePresent

### ISSUE THREAD

**Issue by wlsf82** [wlsf82/protractor-helper#114]
It'd be nice if protractor-helper had a method to wait for an alert to be present, so that I wouldn't need to write something like:

`browser.wait(protractor.ExpectedConditions.alertIsPresent(), 5000);`

Instead, I'd write something like:

`protractorHelper.waitForAlertPresence()` or `protractorHelper.waitForAlertToBePresent()`.

**Comment by wlsf82** [comment]
@pedrohyvo, would you like to pair on this to get your hands a bit dirty with some code!

**Comment by pedrohyvo** [comment]
@wlsf82 yes, should be awesome to put my hands on some code for this project 💯

**Comment by pedrohyvo** [comment]
@wlsf82 do you have any ideas how to work on this issue?

**Comment by wlsf82** [comment]
> wlsf82, do you have any ideas on how to work on this issue?

I do, @pedrohyvo. It's gonna be very similar to the already existing functions.
I suggest that you start looking at the codebase (`src/` directory) and get used to it.

**Comment by pedrohyvo** [comment]
@wlsf82 assign this issue to myself and I'll start working on it soon. If I need any help I'll ask here

**Comment by wlsf82** [comment]
> @wlsf82 assign this issue to myself and I'll start working on it soon. If I need any help I'll ask here

@pedrohyvo, you don't necessarily need the issue assigned to yourself to start working on it.
Go aheas, create a PR, and let's move on from there.
How does that sound?

**Comment by wlsf82** [comment]
@pedrohyvo, I've assigned the issue to you. Sorry for the previous answer (reading it now, it felt a bit rude on my side.)
