### ISSUE TITLE
Add MIT license badge

### ISSUE THREAD

**Issue by pedrohyvo** [wlsf82/protractor-helper#115]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Just to add MIT license on the top of README.md
<img width="80" alt="image" src="https://user-images.githubusercontent.com/15241188/104740576-1baaaf80-5716-11eb-8764-895b76607020.png">

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by pedrohyvo** [comment]
@wlsf82 if you agree, just assign to myself and I'll commit this change shortly

**Comment by wlsf82** [comment]
Remember to update the PT-BR version as well, please.

**Comment by pedrohyvo** [comment]
@wlsf82 created a PR with both README versions updated.

**Comment by wlsf82** [comment]
Closed by #116, thanks to @pedrohyvo! :rock:
