### ISSUE TITLE
Update credits section of GitHub Page

### ISSUE THREAD

**Issue by wlsf82** [wlsf82/protractor-helper#117]
Here's where you can find the outdated info https://github.com/wlsf82/protractor-helper/blob/master/index.md#credits.

And here's the updated one https://github.com/wlsf82/protractor-helper#credits.

**Comment by pedrohyvo** [comment]
@wlsf82 assign to me and I can fix this issue quickly

**Comment by pedrohyvo** [comment]
@wlsf82 here you go! review when you have time please
