### ISSUE TITLE
Fix basic example from docs

### ISSUE THREAD

**Issue by wlsf82** [wlsf82/protractor-helper#123]
On https://github.com/wlsf82/protractor-helper#basic-example, it mentions testing a sign up functionality, but instead, it seems it's testing a sign in functionality since on a sign up I'd expect a `confirmPasswordField` too.

To avoid confusion, lets update it replacing all mentions of 'sign up' and signup' to 'sign in' and signin'

> Note: Remember to update it on https://github.com/wlsf82/protractor-helper/blob/master/docs/PT-BR/README.md#exemplo-básico too.

**Comment by cp-urvi-k** [comment]
@wlsf82 Can i fix this?

**Comment by wlsf82** [comment]
> @wlsf82 Can I fix this?

Sure, I'll assign it to you. Thanks!

**Comment by cp-urvi-k** [comment]
@wlsf82 Hey, it's done. 
Pull request: https://github.com/wlsf82/protractor-helper/pull/128
Please let me know if there any issue, I don't know Portuguese , but i tried  Please review. :)

**Comment by wlsf82** [comment]
> @wlsf82 Hey, it's done.
> Pull request: #128
> Please let me know if there any issue, I don't know Portuguese , but i tried Please review. :)

Hi, @cp-urvi-k, thanks for your contribution to protractor-helper!
I've made some suggestions on your PR, I've pushed the changes already, and it's already merged. :tada:
