### ISSUE TITLE
Autocomplete on VS Code

### ISSUE THREAD

**Issue by rosariotech** [wlsf82/protractor-helper#131]
I use your lib a lot and it would be great if somehow the VS Code could autocomplete the methods. At least mine doesn't do.

**Comment by wlsf82** [comment]
Hi, @rosariotech 👋
I recommend you reading the following blog post https://link.medium.com/sBMywbATcdb

**Comment by wlsf82** [comment]
Also available in Portuguese https://talkingabouttesting.com/2020/04/29/lancamento-do-protractor-helper-versao-4-1-1/

**Comment by wlsf82** [comment]
Hi, @rosariotech, did you have a chance to look at the article? Are you using a version previous to 4.1.1? If so, can we close this issue?

**Comment by rosariotech** [comment]
OK man. I'll read. I'm using the latest release and solved this.

I was importing the lib like this "**const helper = require('protractor-helper')**". When I changed to "**import helper from 'protractor-helper'**" it all worked fine.

Thanks again.
