### ISSUE TITLE
Add vulnerabilities badge on README.me

### ISSUE THREAD

**Issue by wlsf82** [wlsf82/protractor-helper#132]
And on `docs/PT-BR/README.me`

See https://snyk.io/test/npm/protractor-helper/4.1.12

**Comment by jzandag** [comment]
can you assign this to me please?

**Comment by wlsf82** [comment]
> can you assign this to me please?

Hi, @jzandag!
Thanks for your interest in contributing to protractor-helper.
The issue is now assigned to you. 🚀

**Comment by wlsf82** [comment]
Ah, and since this is gonna be your first contribution to protractor-helper, please update the credits section of the `README.md` file (on https://github.com/wlsf82/protractor-helper#credits), and also on `docs/PT-BR/README.MD` and `index.md`.

**Comment by jzandag** [comment]
Thanks for giving this opportunity!

**Comment by wlsf82** [comment]
Closed by https://github.com/wlsf82/protractor-helper/pull/139.
