### ISSUE TITLE
Update CHANGELOG.md to make it more useful

### ISSUE THREAD

**Issue by wlsf82** [wlsf82/protractor-helper#18]
### Description

The CHANGELOG.md file needs to be updated with more useful information, and less useless info.

### Other comments

Here are some ideas:
- split it into main changes (e.g., new features, bug fixes, useful documentation updates, deprecation notifications), and all changes (including updates of versions, dependencies, npm scripts);
- use other nice CHANGELOGS as a reference (e.g., https://github.com/angular/protractor/blob/master/CHANGELOG.md, https://www.gocd.org/releases/, https://docs.cypress.io/guides/references/changelog.html#3-1-4, https://github.com/angular/protractor/blob/selenium4/CHANGELOG.md)
- include commit hashes.

> We could also update the `README.md` file with a link to the `CHANGELOG.md` file, and then have a call-to-action like: "Interested in the latest version of protractor-helper? Take a look at our changelog."

**Comment by narendraprasadr** [comment]
Hi,

Do we have options of validating the table data ? using these helpers like finding how many rows table has and so on....

Thanks
Narendra

**Comment by PauloGoncalvesBH** [comment]
> Hi,
> 
> Do we have options of validating the table data ? using these helpers like finding how many rows table has and so on....
> 
> Thanks
> Narendra

 Hello Narendra,

 Unhappy we don't have options for that yet, but you can open a issue and we will analyze.

**Comment by wlsf82** [comment]
I'll close this issue since we have improved the changelog, not adding unnecessary information on it anymore.
