### ISSUE TITLE
Implement deprecation warnings

### ISSUE THREAD

**Issue by wlsf82** [wlsf82/protractor-helper#24]
### Description

The functions `getBodyElementFromCurrentBrowserOrBrowserInstance` and `openNewBrowserInTheSamePage` will soon be deprecated, so we need to implement a mechanism to warn users about it.

### Other comments

This will require research on how to do it.
Such an implementation can be useful for future changes as well.

**Comment by PauloGoncalvesBH** [comment]
### Important:
 Implement too on all new solutions created on PR #25.

To act on that issue is needed the conclusion of the PR #25.
