### ISSUE TITLE
Do we have options of validating the table data ? using these helpers like finding how many rows table has and so on....

### ISSUE THREAD

**Issue by narendraprasadr** [wlsf82/protractor-helper#29]
Do we have options of validating the table data ? using these helpers like finding how many rows table has and so on....

**Comment by PauloGoncalvesBH** [comment]
@wlsf82  It's possible to create a methot for that?

**Comment by wlsf82** [comment]
@narendraprasadr, could you explain a little bit more what you are trying to achieve? A real example would be great.

**Comment by narendraprasadr** [comment]
Like validating a row data in the table. Example for the table is in the below website:

http://demo.guru99.com/test/web-table-element.php

**Comment by PauloGoncalvesBH** [comment]
You wanna validate if a _Company_ have a X value on _% Change_? A example.

**Comment by PauloGoncalvesBH** [comment]
Or if have a X value on the column _% Change_? If you explain more, will help us.

**Comment by narendraprasadr** [comment]
Exactly correct it's like fetching value from the table....

**Comment by wlsf82** [comment]
I don’t think we need to implement a new function for that.
My suggestion would be that you should locate all the table cels of the specific table you want to check using `element.all`, then you can iterate on every cel and do your verification, maybe even using of of our existing functions, such as `waitForTextToBePresentInElement`

**Comment by narendraprasadr** [comment]
Ok I was not aware of it thankq... Do you have any documents for each
functionality ?

**Comment by wlsf82** [comment]
https://www.w3schools.com/jsref/jsref_foreach.asp

**Comment by PauloGoncalvesBH** [comment]
https://github.com/wlsf82/protractor-helper#waitfortexttobepresentinelement

**Comment by wlsf82** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach
