### ISSUE TITLE
Refactor inputFieldInteractions.js:src/inputFieldInteractions.js

### ISSUE THREAD

**Issue by wlsf82** [wlsf82/protractor-helper#34]
I've selected [**inputFieldInteractions.js:src/inputFieldInteractions.js**](https://github.com/wlsf82/protractor-helper/blob/ce859198172cc7c5058242c632b29d01ea5e8d6c/src/inputFieldInteractions.js#L1-L117) for refactoring, which is a unit of **20** lines of code. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Short Units of Code** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the length of code units to 15 lines of code.
- **Why**❓ 
Small units are easier to analyse, test and reuse.
- **How** 🔧 
When writing new units, don't let them grow above 15 lines of code. When a unit grows beyond this, split it in smaller units of no longer than 15 lines.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by PauloGoncalvesBH** [comment]
This issue can be resolved after the version 4.0.0.

**Comment by wlsf82** [comment]
I'm closing this issue without fixing it since there's nothing we can do for now to reduce the size of the mentioned file.
