### ISSUE TITLE
setTimeout work only to some methods

### ISSUE THREAD

**Issue by PauloGoncalvesBH** [wlsf82/protractor-helper#38]
**Describe the bug**
The setTimeout method work only to the following methods:
-   getBodyElementFromCurrentBrowserOrBrowserInstance
-   openNewBrowserInTheSamePage
-   isCurrentUrlDifferentFromBaseUrl
-   scrollToElementWhenVisible
-   scrollToElement

**Expected behavior**
Expected to work to any method.

**Comment by wlsf82** [comment]
Closed by #39.
