### ISSUE TITLE
Refactor 7 lines occurring 3 times in 2 files: inputFieldInteractions.js, misc.js

### ISSUE THREAD

**Issue by wlsf82** [wlsf82/protractor-helper#40]
I've selected for refactoring 7 lines of code which are duplicated in 2 file(s) ([1](https://github.com/wlsf82/protractor-helper/blob/1e141544bd7676429bc1572cf7149fdc2646cdab/src/inputFieldInteractions.js#L60-L66), [2](https://github.com/wlsf82/protractor-helper/blob/1e141544bd7676429bc1572cf7149fdc2646cdab/src/inputFieldInteractions.js#L18-L24), [3](https://github.com/wlsf82/protractor-helper/blob/1e141544bd7676429bc1572cf7149fdc2646cdab/src/misc.js#L37-L43)).  Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Code Once** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Do not copy code.
- **Why**❓ 
When code is copied, bugs need to be fixed in multiple places. This is both inefficient and a source of regression bugs.
- **How** 🔧 
Avoid duplication by never copy/pasting blocks of code and reduce duplication by extracting shared code, either to a new unit or introduce a superclass if the language permits.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

FYI, @PauloGoncalvesBH.

**Comment by PauloGoncalvesBH** [comment]
I don't think that issue can be corrected. Because the duplication here described is the call of a method.
