### ISSUE TITLE
Deprecate openNewBrowserInTheSamePage() function

### ISSUE THREAD

**Issue by wlsf82** [wlsf82/protractor-helper#49]
As a follow up on https://github.com/wlsf82/protractor-helper/issues/24, seems that we forgot to add the deprecation warning for the `openNewBrowserInTheSamePage()` function.

Cc @PauloGoncalvesBH.

**Comment by PauloGoncalvesBH** [comment]
The ``openNewBrowserInTheSamePage()`` function already has deprecation warning.
https://github.com/wlsf82/protractor-helper/blob/8b601f73b6322251e029c53b4c3118120d144f82/src/misc.js#L18
