### ISSUE TITLE
Implement Continuous Delivery

### ISSUE THREAD

**Issue by PauloGoncalvesBH** [wlsf82/protractor-helper#61]
## Implement Continuous Delivery

**Objective:**
- Automate all repetitive task and use best practices from the open source community.
  - Generate tag, changelog, release, commit and publish after approving pull request.
- Standardize commit message.

****

### Steps:
- [ ]  Git commit - Make the repository [commitizen friendly](http://commitizen.github.io/cz-cli/).
- [x]  Pull request - Validate code with Lint and execute all tests.
- Pull request approved:
  - [ ] Bump version using [standard-version package](https://github.com/conventional-changelog/standard-version)
  - [ ] Generate changelog using [standard-version package](https://github.com/conventional-changelog/standard-version).
  - [ ] Create commit using [standard-version package](https://github.com/conventional-changelog/standard-version)
  - [ ] Create tag using [standard-version package](https://github.com/conventional-changelog/standard-version)
  - [ ] Publish on NPM. See more: [Publishing packages to the npm registry with Github Actions](https://help.github.com/pt/actions/automating-your-workflow-with-github-actions/publishing-nodejs-packages#publishing-packages-to-the-npm-registry)

### Needed validation:
Validate locally if the commit message respect the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) specification. Using `git hooks commit-msg`.

**Comment by wlsf82** [comment]
@PauloGoncalvesBH, are you working on this one, or do you intend to?

If not, please unassign yourself from the issue. 🙂

**Comment by PauloGoncalvesBH** [comment]
@wlsf82 I will act on this issue, I have already managed to gather all the necessary information.

**Comment by PauloGoncalvesBH** [comment]
Somente para ficarem ciante, comecei a atuar nessa task, vou entregar essa semana

**Comment by PauloGoncalvesBH** [comment]
@wlsf82 consegue pegar o seu token do NPM e do Github e cadastrar no secrets do repositório?

É preciso que sejam cadastradas com as seguintes nomenclaturas:
1. **NPM_TOKEN**: [Como pegar o token](https://docs.npmjs.com/creating-and-viewing-access-tokens#creating-tokens-on-the-website)
2. **GH_TOKEN**: Escopo deve ser **repo** e **public_repo**. [Como pegar o token](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token)

Essas variáveis são utilizadas para permitir que a biblioteca _semantic-release_ publique versão no [npmjs.com](https://npmjs.com/) e no Github release.

Para mais infos acesse: 
- https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication-for-plugins
- https://github.com/semantic-release/github#github-authentication
- https://github.com/semantic-release/npm#configuration

**Comment by wlsf82** [comment]
> @wlsf82 consegue pegar o seu token do NPM e do Github e cadastrar no secrets do repositório?
> 
> É preciso que sejam cadastradas com as seguintes nomenclaturas:
> 
> 1. **NPM_TOKEN**: [Como pegar o token](https://docs.npmjs.com/creating-and-viewing-access-tokens#creating-tokens-on-the-website)
> 2. **GH_TOKEN**: Escopo deve ser **repo** e **public_repo**. [Como pegar o token](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token)
> 
> Essas variáveis são utilizadas para permitir que a biblioteca _semantic-release_ publique versão no [npmjs.com](https://npmjs.com/) e no Github release.
> 
> Para mais infos acesse:
> 
> * https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication-for-plugins
> * https://github.com/semantic-release/github#github-authentication
> * https://github.com/semantic-release/npm#configuration

@PauloGoncalvesBH, para o `NPM_TOKEN`, deve ser o **Read-only**, **Automation**, ou **Publish**? 
E para o `GH_TOKEN`, quais permissões devo marcar?

**Comment by wlsf82** [comment]
@PauloGoncalvesBH, outra coisa, você acha que vale o esforço visto que não temos tido novas versões, além de sabermos que o Protractor será descontinuado em 2022?

**Comment by PauloGoncalvesBH** [comment]
> @PauloGoncalvesBH, outra coisa, você acha que vale o esforço visto que não temos tido novas versões, além de sabermos que o Protractor será descontinuado em 2022?

Não valeria o esforço 😕 mesmo que não foi implementado consegue usar como material de referência para bibliotecas futuras.
