### ISSUE TITLE
Translate docs/CONTRIBUTING.md to Portuguese

### ISSUE THREAD

**Issue by wlsf82** [wlsf82/protractor-helper#84]

**Comment by doamaral** [comment]
@wlsf82 how about the location of the CONTRIBUTING.md in pt-br? Should we create another folder inside PT-BR folder?

**Comment by wlsf82** [comment]
> @wlsf82 how about the location of the CONTRIBUTING.md in pt-br? Should we create another folder inside PT-BR folder?

@doamaral, I don't think another folder is needed, let's just put it there and make the translated readme link to the right file.
What do you think?

**Comment by wlsf82** [comment]
Close by #100, thanks to @doamaral!
