### ISSUE TITLE
Missing fillFieldWithTextAndPressEnter method on README files

### ISSUE THREAD

**Issue by wlsf82** [wlsf82/protractor-helper#98]
This is a follow-up issue based on the following comment https://github.com/wlsf82/protractor-helper/pull/97#issuecomment-676547272.

The missing method needs to be added on both default and `PT-BR/` `README.md` files.

Also, let's confirm if any other doc files refer to other methods, but not to this one.

Cc @PauloGoncalvesBH.

**Comment by PauloGoncalvesBH** [comment]
@doamaral essa issue é parecida com tudo que atuou. Gostaria de atuar nela?

**Comment by pedrohyvo** [comment]
@wlsf82 could you assign to me this issue that I can start working on it please

**Comment by wlsf82** [comment]
> @wlsf82 could you assign to me this issue that I can start working on it please

Sure, done!

And thanks!

**Comment by wlsf82** [comment]
@pedrohyvo, I'll unassign you from this issue while you're working on https://github.com/wlsf82/protractor-helper/issues/117.

Let's keep the WIP (work-in-progress) limited to one issue at a time.

**Comment by pedrohyvo** [comment]
@wlsf82 you can re assign to me since the other PR was closed now

**Comment by wlsf82** [comment]
@pedrohyvo, remember to update your fork based on the most up-to-date version of the main repo, please.
